# Generated by Django 5.0.3 on 2025-05-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Core', '0008_remove_profile_image_alter_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_cart',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
