# Generated by Django 5.0.3 on 2025-05-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Core', '0009_profile_saved_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved_cart',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
