# Generated by Django 5.0.3 on 2025-05-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Core', '0010_alter_profile_saved_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
